name: Build and update flake.lock

on: [push, repository_dispatch, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.branch }}

defaults:
  run:
    shell: bash # Enables `-eo pipefail`

jobs:
  matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.matrix.outputs.packages }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set-up-nix-and-cachix

      - id: matrix
        run: ./build_matrix.py | tee $GITHUB_STEP_SUMMARY

  build:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: matrix

    if: needs.matrix.outputs.packages != '[]'

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set-up-nix-and-cachix
        with:
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build .#${{ matrix.package }} --recreate-lock-file --print-build-logs

  update-flake-lock:
    name: Update flake.lock
    runs-on: ubuntu-latest
    needs: build

    # See: https://github.com/actions/runner/issues/491
    if: |
      always()
      && (needs.build.result == 'success' || needs.build.result == 'skipped')
      && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set-up-nix-and-cachix

      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: nix flake update --commit-lock-file
      # This might fail because main has been pushed to since the workflow
      # started, these runs will trigger another workflow run so it should be
      # fine to ignore errors...?
      - run: git push || true

  # See: https://github.com/orgs/community/discussions/26822
  check-failed:
    name: Check for failed builds
    runs-on: ubuntu-latest
    needs: build

    if: always()

    steps:
      - run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
